### ISSUE TITLE
Bug Report: i can't build it 

### ISSUE THREAD

**Issue by beeanie** [indigoUan/slenderman-source#1]
source/PlayState.hx:3867: characters 9-28 : Unknown identifier : storyDifficultyText
source/PlayState.hx:3884: characters 9-28 : Unknown identifier : storyDifficultyText 

this the error that it gave me when i build with macos

**Comment by indigoUan** [comment]
lol
lmao

**Comment by indigoUan** [comment]
At line 118 you can see a `#if windows`, it's not a bug, MacOS simply isn't compatoble with discord functions.
